Zk02
Nasruddinkhan/labeasy pull request #28
Opened 2021-06-22 19:28 UTC by mmzaid

2021-06-22 19:54 UTC, Nasruddinkhan requested changes
Added few comments please check

2021-06-22 19:54 UTC, Nasruddinkhan commented on src/main/java/com/labeasy/controller/CityController.java
> +	public CityController(MasterService masterService) {
Add constructor autowired

2021-06-22 19:54 UTC, Nasruddinkhan commented on src/main/java/com/labeasy/controller/PinCodeController.java
> +	public PinCodeController(MasterService masterService) {
Add constructor autowired

2021-06-22 19:54 UTC, Nasruddinkhan commented on src/main/java/com/labeasy/entity/City.java
> +	@OneToMany(mappedBy = "city",cascade = CascadeType.ALL)
Add lazy intilization

2021-06-24 12:08 UTC, mmzaid commented
added missing autowired anotation and lazy loding in city module

2021-06-24 17:57 UTC, Nasruddinkhan approved these changes

2021-06-24 17:57 UTC, merged